apiVersion: v1
kind: Service
metadata:
  name: 8byte-app-service
  labels:
    app: 8byte-app
spec:
  selector:
    app: 8byte-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP